-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS resume_pro_db;

-- Use the newly created database
USE resume_pro_db;

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(128) PRIMARY KEY, -- Firebase UID
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create resumes table
CREATE TABLE IF NOT EXISTS resumes (
    id VARCHAR(128) PRIMARY KEY, -- Can be UUID generated by backend or Firestore Doc ID
    user_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    data JSON NOT NULL, -- Store resume data as JSON string
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create cover_letters table
CREATE TABLE IF NOT EXISTS cover_letters (
    id VARCHAR(128) PRIMARY KEY, -- Can be UUID generated by backend or Firestore Doc ID
    user_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    data JSON NOT NULL, -- Store cover letter data as JSON string
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Example: Insert a dummy user (only if not using Firebase Auth directly)
-- For this project, users will be created via Firebase Auth client-side,
-- then their UID will be used here.
-- INSERT INTO users (id, email) VALUES ('someFirebaseUID123', 'test@example.com');
